# Generated by Django 2.0.2 on 2018-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180318_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static_img/default_img.jpg', upload_to='profile/%Y/%m'),
        ),
    ]
