# Generated by Django 2.0.2 on 2018-04-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20180406_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='reple',
            name='author_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
